name: 'Amazon ECS Task Definition Jinja2 based renderer'
description: 'Helm like generation of AWS ECS Task definition'
branding:
  icon: 'cloud'
  color: 'blue'
inputs:
  task-definition:
    description: 'The path to the ECS task definition JSON file'
    required: true
  values:
    description: 'Path to the file or directory holding values interpolating the task definition. Multiple space separated paths are possible.'
    required: true
  image:
    description: 'The image varible override'
outputs:
  task-definition:
    description: 'The path to the rendered task definition file'
runs:
  using: 'docker'
  image: 'Dockerfile'
