FROM python:3.7-slim

# Install libraries
COPY requirements.*txt /

# Base software
RUN apt update \
    && apt install -y libmagic-dev git vim

# Python libraries
RUN pip install -r requirements.txt \
    && pip install -r requirements.dev.txt